# Generated by Django 2.1.5 on 2019-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='misc',
            field=models.TextField(default='D'),
            preserve_default=False,
        ),
    ]
