# Generated by Django 2.1.5 on 2019-01-21 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='misc',
        ),
    ]
