# Generated by Django 2.1.5 on 2019-02-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('myinfo', models.TextField()),
            ],
        ),
    ]
